lab3:
	cd ./lab3/src/ && g++ section.h -c -std=c++14
	cd ./lab3/src/ && g++ student.h -c -std=c++14
	cd ./lab3/src/ && g++ instructor.h -c -std=c++14
	cd ./lab3/src/ && g++ term.h -c -std=c++14
	cd ./lab3/src/ && g++ college.cpp -c -std=c++14
	cd ./lab3/src/ && g++ io.cpp -c -std=c++14 
	cd ./lab3/src/ && g++ main.cpp -o main.exe -std=c++14 -lstdc++fs  && ./main.exe
	cd ./lab3/src/ && rm *.o && rm *.gch